FROM node:lts-alpine as build-stage
WORKDIR /homepage
COPY package*.json ./

RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine as production-stage
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/homepage.conf /etc/nginx/conf.d/homepage.conf

COPY --from=build-stage ./homepage/dist /usr/share/nginx/html/
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
